pipeline:
  verify-lint:
    image: quay.io/presslabs/gitfs-test:${PYTHON_VERSION}
    commands:
      - pip install black
      - make verify-lint

  test:
    image: quay.io/presslabs/gitfs-test:${PYTHON_VERSION}
    privileged: true
    environment:
      - PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache
      - PYTHON=${PYTHON_VERSION}
    commands:
      - chmod 660 /dev/fuse
      - echo user_allow_other | tee -a /etc/fuse.conf > /dev/null
      - chmod 644 /etc/fuse.conf
      - git config --global user.email "drone@example.com"
      - git config --global user.name "Drone CI"
      - make test
    volumes:
      - /var/cache/apt/:/var/cache/apt/

  trigger-docs-build:
    image: plugins/downstream
    server: https://drone.presslabs.net
    fork: true
    secrets: [DRONE_TOKEN]
    repositories:
      - presslabs/docs
    when:
      branch: master
      event: push

matrix:
  include:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.4
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.8
