FROM ubuntu:18.04

ARG PYTHON=3.7

RUN apt-get update && apt-get install -qy build-essential python-pip python-virtualenv python-dev software-properties-common libfuse-dev fuse git libffi-dev python${PYTHON}-dev libgit2-dev python3-pip

COPY test_requirements.txt requirements.txt /
RUN if [ "$PYTHON" = "2.7" ] ; then pip install -r /test_requirements.txt; else pip3 install -r /test_requirements.txt; fi
