#!/bin/sh
echo I am provisioning...
sudo sh -c 'date > /etc/vagrant_provisioned_at'
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q python-software-properties
sudo add-apt-repository ppa:presslabs/gitfs
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -q python-virtualenv python-dev libffi-dev build-essential libgit2-dev git-core python3.4-dev
sudo adduser "$USER" fuse
sudo sh -c "echo 'user_allow_other' >> /etc/fuse.conf"
virtualenv -q --setuptools /home/vagrant/gitfs -ppython3.4
echo "source $HOME/gitfs/bin/activate" >> "$USER/.bashrc"
echo Installing cffi
/home/vagrant/gitfs/bin/pip install -q 'cffi'
echo Installing requirements
/home/vagrant/gitfs/bin/pip install -q -r /vagrant/test_requirements.txt
echo Configuring git
git config --global user.email "vagrant@localhost"
git config --global user.name "Vagrant"
echo Installing gitfs
"$HOME/gitfs/bin/pip" install -q -e /vagrant
