#!/bin/sh
set -e
$VIRTUAL_ENV/bin/pip install -e .
$VIRTUAL_ENV/bin/gitfs $BARE_REPO $MNT_DIR -o repo_path=$REPO_DIR,fetch_timeout=.1,merge_timeout=.1,allow_other=true,foreground=true,log=log.txt,debug=true,idle_fetch_timeout=.1 & echo "$$!" > $GITFS_PID
MOUNT_PATH=$MNT_DIR REPO_PATH=$REPO_DIR REPO_NAME=$REPO_NAME REMOTE=$REMOTE $VIRTUAL_ENV/bin/py.test --cov-report term-missing --cov gitfs $TESTS
kill -9 `cat $GITFS_PID`
sudo umount -f $MNT_DIR
rm -rf $TEST_DIR
